
use customer_behavior_data
select * from post_customer_behavior_data

----------------------------------------------------------------------------------------

-- what is the total revenue generated by male vs female
CREATE VIEW v_revenue_by_gender AS
SELECT 
    gender,
    SUM(purchase_amount) AS total_revenue
FROM post_customer_behavior_data
GROUP BY gender;
-- which customer used discount but still spent more than the average purchase amount

CREATE VIEW v_discount_high_spenders AS
SELECT customer_id, purchase_amount  
FROM post_customer_behavior_data 
WHERE discount_applied = 'Yes' 
AND purchase_amount >= (
    SELECT AVG(purchase_amount) 
    FROM post_customer_behavior_data
);

----------------------------------------------------------------------------------------

-- which are top 5 products with highest average review rating
CREATE VIEW v_top_rated_products AS
WITH high_average AS
(
    SELECT 
        item_purchased,
        ROUND(AVG(review_rating),2) AS highest_average_rating
    FROM post_customer_behavior_data
    GROUP BY item_purchased
)
SELECT *
FROM high_average;
----------------------------------------------------------------------------------------

-- compare the average purchase amonut between standard and express_shipping
CREATE VIEW v_shipping_comparison AS
SELECT 
    shipping_type,
    AVG(purchase_amount) AS average_purchase
FROM post_customer_behavior_data
WHERE shipping_type IN ('Express','Standard')
GROUP BY shipping_type;

---------------------------------------------------------------------------------------- 

-- compare between average spend ,total_revenue by subscription , un sub

CREATE VIEW v_subscription_analysis AS
SELECT  
    subscription_status,
    COUNT(customer_id) AS total_customers,
    AVG(purchase_amount) AS average_spend,
    SUM(purchase_amount) AS total_revenue
FROM post_customer_behavior_data
GROUP BY subscription_status;

-----------------------------------------------------------------------------------------

 -- which are top 5 products with highest percentage of purchase and discount_applied
CREATE VIEW v_discount_rate_products AS
WITH high_rate AS
(
    SELECT 
        item_purchased,
        ROUND(
            SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) * 100.0 / COUNT(*),
            2
        ) AS discount_rate
    FROM post_customer_behavior_data
    GROUP BY item_purchased
)
SELECT *
FROM high_rate;

-----------------------------------------------------------------------------------------

-- segment customer

CREATE VIEW v_customer_segments AS
WITH customer_type AS
(
    SELECT 
        customer_id,
        previous_purchases,
        CASE 
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segments
    FROM post_customer_behavior_data
)
SELECT 
    customer_segments,
    COUNT(*) AS total_customers
FROM customer_type
GROUP BY customer_segments;

--------------------------------------------------------------------------------------------

-- top 3 of purchased_item within category

CREATE VIEW v_top_items_category AS
WITH top_purchased_items AS
(
    SELECT 
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER
        (
            PARTITION BY category
            ORDER BY COUNT(customer_id) DESC
        ) AS item_rank
    FROM post_customer_behavior_data
    GROUP BY category, item_purchased
)
SELECT *
FROM top_purchased_items;

---------------------------------------------------------------------------------------

-- customer with top 5 pervious_purcahses

CREATE VIEW v_repeat_buyers AS
SELECT 
    subscription_status,
    COUNT(customer_id) AS repeat_buyers
FROM post_customer_behavior_data 
WHERE previous_purchases > 5
GROUP BY subscription_status;

----------------------------------------------------------------------------------------

-- revenue contribution for age group

CREATE VIEW v_revenue_by_age_group AS
SELECT 
    age_group,
    SUM(purchase_amount) AS revenue_contribution
FROM post_customer_behavior_data 
GROUP BY age_group;